<?php

namespace Oxch\Composer;

class CleanupRules
{
    public static function getRules()
    {
        // Default patterns for common files
        $docs = 'README* CHANGELOG* FAQ* CONTRIBUTING* HISTORY* UPGRADING* UPGRADE* package* demo example examples doc docs readme* changelog* composer*';
        $tests = '.travis.yml .scrutinizer.yml phpcs.xml* phpcs.php phpunit.xml* phpunit.php test tests Tests travis patchwork.json';

        return [
            'anahkiasen/former' => [$docs, $tests],
            'anahkiasen/html-object' => [$docs, 'phpunit.xml* tests/*'],
            'anahkiasen/rocketeer' => [$docs, $tests],
            'anahkiasen/underscore-php' => [$docs, $tests],
            'barryvdh/composer-cleanup-plugin' => [$docs, $tests],
            'barryvdh/laravel-debugbar' => [$docs, $tests],
            'barryvdh/laravel-ide-helper' => [$docs, $tests],
            'bllim/datatables' => [$docs, $tests],
            'cartalyst/sentry' => [$docs, $tests],
            'classpreloader/classpreloader' => [$docs, $tests],
            'd11wtq/boris' => [$docs, $tests],
            'danielstjules/stringy' => [$docs, $tests],
            'dflydev/markdown' => [$docs, $tests],
            'dnoegel/php-xdg-base-dir' => [$docs, $tests],
            'doctrine/annotations' => [$docs, $tests, 'bin'],
            'doctrine/cache' => [$docs, $tests, 'bin'],
            'doctrine/collections' => [$docs, $tests],
            'doctrine/common' => [$docs, $tests, 'bin lib/vendor'],
            'doctrine/dbal' => [$docs, $tests, 'bin build* docs2 lib/vendor'],
            'doctrine/inflector' => [$docs, $tests],
            'dompdf/dompdf' => [$docs, $tests, 'www'],
            'filp/whoops' => [$docs, $tests],
            'guzzle/guzzle' => [$docs, $tests],
            'guzzlehttp/guzzle' => [$docs, $tests],
            'guzzlehttp/oauth-subscriber' => [$docs, $tests],
            'guzzlehttp/streams' => [$docs, $tests],
            'imagine/imagine' => [$docs, $tests, 'lib/Imagine/Test'],
            'intervention/image' => [$docs, $tests, 'public'],
            'ircmaxell/password-compat' => [$docs, $tests],
            'jakub-onderka/php-console-color' => [$docs, $tests, 'build.xml example.php'],
            'jakub-onderka/php-console-highlighter' => [$docs, $tests, 'build.xml'],
            'jasonlewis/basset' => [$docs, $tests],
            'jeremeamia/SuperClosure' => [$docs, $tests, 'demo'],
            'kriswallsmith/assetic' => [$docs, $tests],
            'laravel/framework' => [$docs, $tests, 'build'],
            'leafo/lessphp' => [$docs, $tests, 'Makefile package.sh'],
            'league/flysystem' => [$docs, $tests],
            'league/stack-robots' => [$docs, $tests],
            'maximebf/debugbar' => [$docs, $tests, 'demo'],
            'mccool/laravel-auto-presenter' => [$docs, $tests],
            'mockery/mockery' => [$docs, $tests],
            'monolog/monolog' => [$docs, $tests],
            'mrclay/minify' => [$docs, $tests, 'MIN.txt min_extras min_unit_tests min/builder min/config* min/quick-test* min/utils.php min/groupsConfig.php min/index.php'],
            'mtdowling/cron-expression' => [$docs, $tests],
            'mustache/mustache' => [$docs, $tests, 'bin'],
            'nesbot/carbon' => [$docs, $tests],
            'nikic/php-parser' => [$docs, $tests, 'test_old'],
            'oyejorge/less.php' => [$docs, $tests],
            'patchwork/utf8' => [$docs, $tests],
            'phenx/php-font-lib' => [$docs, $tests . 'www'],
            'phpdocumentor/reflection-docblock' => [$docs, $tests],
            'phpoffice/phpexcel' => [$docs, $tests, 'Examples unitTests changelog.txt'],
            'phpseclib/phpseclib' => [$docs, $tests, 'build'],
            'predis/predis' => [$docs, $tests, 'bin'],
            'psr/log' => [$docs, $tests],
            'psy/psysh' => [$docs, $tests],
            'rcrowe/twigbridge' => [$docs, $tests],
            'simplepie/simplepie' => [$docs, $tests, 'build compatibility_test ROADMAP.md'],
            'stack/builder' => [$docs, $tests],
            'swiftmailer/swiftmailer' => [$docs, $tests, 'build* notes test-suite create_pear_package.php'],
            'symfony/inflector' => [$docs, $tests],
            'symfony/browser-kit' => [$docs, $tests],
            'symfony/class-loader' => [$docs, $tests],
            'symfony/console' => [$docs, $tests],
            'symfony/css-selector' => [$docs, $tests],
            'symfony/debug' => [$docs, $tests],
            'symfony/dom-crawler' => [$docs, $tests],
            'symfony/event-dispatcher' => [$docs, $tests],
            'symfony/filesystem' => [$docs, $tests],
            'symfony/finder' => [$docs, $tests],
            'symfony/http-foundation' => [$docs, $tests],
            'symfony/http-kernel' => [$docs, $tests],
            'symfony/process' => [$docs, $tests],
            'symfony/routing' => [$docs, $tests],
            'symfony/security' => [$docs, $tests],
            'symfony/security-core' => [$docs, $tests],
            'symfony/var-dumper' => [$docs, $tests],
            'symfony/property-access' => [$docs, $tests],
            'symfony/translation' => [$docs, $tests],
            'symfony/translation-contracts' => [$docs, $tests],
            'symfony/workflow' => [$docs, $tests],
            'symfony/config' => [$docs, $tests],
            'symfony/dependency-injection' => [$docs, $tests],
            'tijsverkoyen/css-to-inline-styles' => [$docs, $tests],
            'twig/twig' => [$docs, $tests],
            'venturecraft/revisionable' => [$docs, $tests],
            'vlucas/phpdotenv' => [$docs, $tests],
            'willdurand/geocoder' => [$docs, $tests],
            'barryvdh/laravel-dompdf' => [$docs],
            'league/csv' => [$docs],
            'reliese/laravel' => [$docs, $tests],
            'stevenmaguire/oauth2-keycloak' => [$docs, $tests],
            'hamcrest/hamcrest-php' => [$docs, $tests],
            'phpunit/phpunit' => [$docs, $tests],
            'phpunit/php-code-coverage' => [$docs, $tests],
            'phpunit/php-token-stream' => [$docs, $tests],
            'phpmd/phpmd' => [$docs],
            'sebastian/diff' => [$docs, $tests],
            'sebastian/comparator' => [$docs, $tests],
            'sebastian/global-state' => [$docs, $tests],
            'sabberworm/php-css-parser' => [$docs, $tests],
            'phar-io/manifest' => [$docs, $tests, 'examples'],
            'phar-io/version' => [$docs, $tests],
            'theseer/tokenizer' => [$docs, $tests],
            'mk-j/php_xlsxwriter' => [$docs, 'examples testbench example example-cli'],
            'markbaker/complex' => [$docs, 'examples'],
            'markbaker/matrix' => [$docs, 'examples'],
            'fzaninotto/faker' => [$docs, $tests]
        ];
    }
}
